# -*- coding: utf-8 -*-
"""AdvanceMathematics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNQ5m5pAARA-xPR5S35mGkri2DAJVNHf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

data = pd.read_csv('data.csv', encoding='latin1')
no2 = data["no2"].dropna().values

roll = 102303139

a = 0.05 * (roll % 7)
b = 0.3 * ((roll % 5) + 1)

print("a =", a)
print("b =", b)

data.head()

print(data.columns)

z = no2 + a * np.sin(b * no2)
counts, edges = np.histogram(z, bins=50, density=True)
centers = (edges[:-1] + edges[1:]) / 2

def pdf(z, lam, mu, c):
    value = -lam * (z - mu) ** 2
    value = np.clip(value, -500, 500)
    return c * np.exp(value)

start = [0.01, np.mean(z), 1]
best, _ = curve_fit(pdf, centers, counts, p0=start)

#printing the parameter values
lam = best[0]
mu = best[1]
c = best[2]

print("Lambda =", lam)
print("Mu =", mu)
print("c =", c)

smooth = np.linspace(min(z), max(z), 500)
plt.hist(z, bins=50, density=True)
plt.plot(smooth, pdf(smooth, lam, mu, c))
plt.xlabel("z")
plt.ylabel("Density")
plt.title("Histogram and Fitted Curve")
plt.show()